config/routes.rb
Rails.application.routes.draw do
   
    resources :articles #do     
    get 'welcome/index'    
    get 'articles/new'
    post 'articles/new'

    get 'articles/4/edit'
    get 'articles/4/destroy'

  resources :dashboards
  resources :posts #do
  get 'posts/new'
  post 'posts/new'
  get 'posts/4/edit'
  get 'posts/4/destroy'
  
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  
	
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  get 'page/index'
  root 'page#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title,
  			presence: true

  validates :content,
  			presence: true

  validates :user,
  			presence: true

  def to_s
  	 title
  end
end
 	

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :destroy

  validates :first_name,
  			presence: true
  validates :last_name,
  			presence: true
  validates :email,
  			presence: true,
  			uniqueness: true,
  			format: {
  				with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  		 			}

 def to_s
 		"#{first_name} #{last_name}"
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  	def current_user
  		User.where(id: session[:user_id]).first
  	end
  	helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
	    @articles = Article.all
	  end
	def show
	    @article = Article.find(params[:id])
	  end
	def new
		@article = Article.new
  	end

  	def edit
	  @article = Article.find(params[:id])
	end

  	def create
	  @article = Article.new(article_params)
	 
	  @article.save
	  redirect_to @article
	end

	def update
		@article = Article.find(params[:id])
		 
	    if @article.update(article_params)
	        redirect_to @article
	    else
	    	render 'edit'
	 	end
	end

	 def destroy
	    @article = Article.find(params[:id])
	    @article.destroy
	 
	    redirect_to articles_path
	  end

	 
	private
	  def article_params
	    params.require(:article).permit(:title, :text)
	  end
end

app/controllers/dashboards_controller.rb
  class DashboardsController < ApplicationController
    before_action :set_dashboard, only: [:show, :edit, :update, :destroy]

    # GET /dashboards
    def index
      @dashboards = Dashboard.all
    end

    # GET /dashboards/1
    def show
    end

    # GET /dashboards/new
    def new
      @dashboard = Dashboard.new
    end

    # GET /dashboards/1/edit
    def edit
    end

    # POST /dashboards
    def create
      @dashboard = Dashboard.new(dashboard_params)

      if @dashboard.save
        redirect_to @dashboard, notice: 'Dashboard was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /dashboards/1
    def update
      if @dashboard.update(dashboard_params)
        redirect_to @dashboard, notice: 'Dashboard was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /dashboards/1
    def destroy
      @dashboard.destroy
      redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_dashboard
        @dashboard = Dashboard.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def dashboard_params
        params[:dashboard]
      end
  end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]
  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit 
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: "Not authorized ! Please Login"
      else
        if @post && @post.user != current_user
          redirect_to root_path, alert: "Not authorized ! Only #{@post.user} has access to this post"
      end
    end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to new_dashboard_path, notice: 'Logged in !'
  	else
  		redirect_to login_path, notice: 'Incorrect username or password !'

  	end
  end
  def destroy 
  	session[:user_id] = nil
  	redirect_to root_url, notice: 'Logged out !'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= link_to 'New article', new_article_path %>


<h1>Listing articles</h1>
 
<table style="border-collapse: collapse; font-size:14px" border="1px" cellpadding="10px">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Details</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
this is dashboard

app/views/dashboards/new.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<div class = "jumbotron">
<div class="alert alert-success" role="alert">
Hello this is the dashboard. You can post your blogs, thoughts and forums by clicking in the blog menu bar. Feel free to share your ideas, thoughts and what goes on in the upcoming episodes of One Piece. You can post you queries and theories etc.. and communicate with other manga readers and viewers. Keep reading and watching. </br></br> Snaps

	<%= image_tag("13.jpg", :alt => "rss feed") %>
	<%= image_tag("12.jpg", :alt => "rss feed") %>
	<%= image_tag("11.jpg", :alt => "rss feed") %>
</div>
</div>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sdpblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

</head>
<body>
  
<div id="user_header">
	 <div class="container">
      <div class="header clearfix">
        <nav>
        	<br>
        	<br>
            <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><%= link_to 'Home', root_path %></li>
            <li role="presentation" class="active"><%= link_to 'Blogs', posts_path %></li>
		      	<li role="presentation" class="active"><%= link_to 'Userlist', users_path %></li>            
            <% if current_user %>
            <li role="presentation" class="active"><%= link_to 'Dashboard', new_dashboard_path %></li>
           	<li role="presentation"class="active"><%= link_to "Log out", logout_path %></li> </br>
           </br><div class="alert alert-success" role="alert"> Logged in as <%= current_user.email %> </div>
  </ul>
		<% else %>          
            <li role="presentation" class ="active"><%= link_to "Log in", login_path %></li>
            <li role="presentation"class="active"><%= link_to "Sign_up", signup_path %></li>
          </ul>
        </nav>
        <% end %>
        <h3> One Piece Blog</h3>
    </br></br>
    <% flash.each do |key, value| %>
	<%= content_tag(:div, class: "alert alert-#{key}") do %>
	<p> <%= value %> </p>
<% end %>
<% end %>	
<%= yield %>
      </div>
	</div>
</div>
	</body>
</html>

app/views/page/index.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<div class = "jumbotron"><div class="alert alert-success" role="alert">
	<p>One piece story </p> <br>
Greatness, Glory, Gold. A Pirate Named Gold Roger also known as the Pirate King has conquered this all. He was executed with an unknown reason but before he died he had revealed his last word about The legendary Treasure named One Piece which was hidden in the Grand Line. 22 years after his Death, A Pirate named Monkey D. Luffy appeared and has only one Goal, To Become the Next "Pirate King" and Find The Treasure "One Piece". This Start The Never Ending Adventure. Monkey D. Luffy, inspired by his childhood hero "Red-Haired" Shanks, sets out on a journey to find the legendary treasure One Piece, to become the new Pirate King, and after eating the devil's fruit gains the power to do so. To accomplish this, he must reach the end of the most deadly and dangerous ocean: The Grand Line. But first he must find a crew.
</br>
</br>
During the course of the story, the crew contend with both other less moral pirate crews and the Marines. The latter are the subordinates of the World Government, who seek justice by ending the Golden Age of Pirates. Many background story elements involve the delicate balance of power between the World Government and the world's most powerful pirate crews. Also, the Craziest Crew in the world .
<br>
<br>
Snaps
	<%= image_tag("9.jpg", :alt => "rss feed") %>
	<%= image_tag("10.jpg", :alt => "rss feed") %>
	<%= image_tag("12.jpg", :alt => "rss feed") %>

	<br><br>
So, please signup and start posting blogs and forums regarding the most popular one piece anime.

</br>

</div></div>
<div class="alert alert-danger" role="alert"><p align = "center"><font size="2">Copyright Sudip Rai, 2016</font></p></div>

app/views/posts/_form.html.erb
<div class = "jumbotron">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      
      <ul>
      <% @post.errors.full_messages.each do |message| %>
       <h4> <li><%= message %></li> </h4>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="alert alert-info" role="alert"> <p align="center"><font size="3"> Blogs </font></p></div>
   <div class="alert alert-success" role="alert">
    <div class="field">
       <p align = "center"> <font size = "2"><%= f.label :title %><br></font></p>
    <p align = "center"><font size = "2"><%= f.text_field :title %></font></p>
  </div>
  <div class="field">
    <p align = "center"><font size = "2"><%= f.label :content %><br></font></p>
    <p align = "center"><font size = "2"><%= f.text_area :content %></font></p>
  </div>
  <div class="actions"> 
     <div class="alert alert-danger" role="alert">
  <p align = "center"> <font size = "2"><%= f.submit %></font></p></div></div>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

<p align = "center"><%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %> </p>

app/views/posts/index.html.erb
<div class = "jumbotron">

<% if current_user %>
<div class="alert alert-success" role="alert"><%= link_to 'Click here to create a new blog', new_post_path %></div>
<% end %><br>
<div class="alert alert-info" role="alert">

<h4>List of Blogs</h4>
<div class="alert alert-danger" role="alert">
Note : After login, you can only edit and delete the blog if you have posted that personally from your account. The other users can only view them. Each blog is authorized by their own users.  So, once you upload a blog , you have the full authority to edit and delete if you login from your account whereas other users only have the permission to read the blog.<br> <br></div>
   <% @posts.each do |post| %>
      Posted by : <%= post.user %> <br><br>
      Title : <%= post.title %> <br><br>
      Content : <%= post.content %> <br> <br>
    <div class="alert alert-warning" role="danger">
      <p align="center"> <font size = "2">
      <%= link_to 'Show', post %>
      <% if current_user && post.user == current_user %><%= link_to 'Edit', edit_post_path(post) %><% end %></td>
      <% if current_user && post.user == current_user %><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %><% end %> </font> </p>  </div>  
      <br><br>
    <% end %>
</div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class = "jumbotron">
	<div class="alert alert-success" role="alert">
Posted by : 
  <%= @post.user %>
<br><br>
 Title : 
 <%= @post.title %>
<br><br>  
 Content :
 <%= @post.content %>
<% if current_user && @post.user == current_user %><br><br>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>
</div>
</div>

app/views/users/_form.html.erb
<div class = "jumbotron">
  
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <h4><li><%= message %></li></h4>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>

<br><div class="alert alert-success" role="alert">
<p align="center"><font size = "3">Users </font></p>
</div>
<div class="alert alert-info" role="alert">

  <div class="field">
    <p align = "center"><font size = "2"><%= f.label :first_name %></font></p>
    <p align = "center"><font size = "2"><%= f.text_field :first_name %></font> </p>
  </div>
  <div class="field">
    <p align = "center"><font size = "2"><%= f.label :last_name %></font></p>
    <p align = "center"><font size = "2"><%= f.text_field :last_name %></font></p>
  </div>
  <div class="field">
    <p align = "center"><font size = "2"><%= f.label :email %></font></p>
    <p align = "center"><font size = "2"><%= f.text_field :email %></font></p>
  </div>
  <div class="field">
    <p align = "center"><font size = "2"><%= f.label :password %></font></p>
    <p align = "center"><font size = "2"><%= f.password_field :password %></font></p>
  </div>
  <div class="field">
  <p align = "center"><font size = "2"><%= f.label :password_confirmation %></font></p>
   <p align = "center"><font size = "2"><%= f.password_field :password_confirmation %></font></p>
  </div>
  <div class="actions">
    <div class="alert alert-danger" role="alert">
<p align = "center"><font size = "2"><%= f.submit %></font></p></div>
          
  </div>
  <% end %> 
</div>
</div>
</div>

app/views/users/edit.html.erb
<div class="jumbotron">
<%= render 'form' %>

<p align = "center"><font size = "2"><%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %></font></p>
</div>

app/views/users/index.html.erb
<div class = "jumbotron">
	<div class="alert alert-success" role="alert">
<p>List of Users</p><br>
    <% @users.each do |user| %>
    First Name :   
  <%= user.first_name %><br><br>
    Last Name:
  <%= user.last_name %><br><br>
    Email :
  <%= user.email %><br><br>
        <div class="alert alert-warning" role="alert"><p align = "center"><font size = "2"><%= link_to 'Show', user %></font></p></div></br></br>
        <% end %>   
</div>
</div>

app/views/users/new.html.erb
<div class = "jumbotron">
	<div class = "jumbotron">
<%= render 'form' %>

<p align = "center"><font size ="2"> <%= link_to 'Userlist', users_path %> </font></p></div>
</div>

app/views/users/show.html.erb
<div class = "jumbotron">
	<div class="alert alert-success" role="alert">
First name:
  <%= @user.first_name %><br><br>
Last name:
  <%= @user.last_name %><br><br>
Email:
  <%= @user.email %><br><br>

<p align="right"><font size="2"><%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> </font> </p>
</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>